### ISSUE TITLE
Angular Grid - event when filter dialog is closed

### ISSUE THREAD

**Issue by Dschuli** [syncfusion/ej2-angular-ui-components#101]
I would be looking for an event that gets triggered a grid filter dialog gets closed. I was able to construct quite a few events from existing events (e.g. when filter dialog is closed via Ok or Cancel button), but was unable to find an event that gets triggered when the filter dialog is closed via a background click.

Would be great to have an event fired when such a filter dialog gets closed - or alternatively a way to prevent closing via background click.

**Comment by sujithvj** [comment]
Hi Dschuli,

Greetings from Syncfusion.

You can achieve this requirement by binding the **destroyed** event to the filter dialog’s instance in the Grid’s **actionComplete** event. This event will be triggered when the filter dialog is closed. Please check the below code snippet,

`// Grid’s actionComplete event function
actionComplete(args){
        if (args.requestType === "filterchoicerequest") {
            args.filterModel.dialogObj.destroyed = this.dialogClose.bind(this);
        }
}

dialogClose(args) {
        // Triggers after filter dialog is closed
        alert('Filter dialog is closed');
}`

We have prepared a sample based on this for your reference. You can find it below,

**Sample:** https://stackblitz.com/edit/angular-nhuwtm?file=app.component.ts

**_Note: Since the dialog’s close events are accessed inside the Grid source to perform the filter operation the filter dialog close cannot be prevented on background click. It would require overriding these events which will cause problems with the Grid filter operations._**

Let us know if you have any concerns.

Regards,
Sujith R

**Comment by Dschuli** [comment]
Thanks , Sujith. Works like a charm!
