### ISSUE TITLE
Sudden errors after component upgrade

### ISSUE THREAD

**Issue by duzenko** [syncfusion/ej2-angular-ui-components#111]
Resizing events in timeline week view fails with tons of console error spam
![image](https://user-images.githubusercontent.com/1481807/88295333-f4929880-cd05-11ea-89c8-8c979db2c0bc.png)

**Comment by duzenko** [comment]
Or, on my localhost it's
`ERROR TypeError: "IsAllDay" is read-only`

**Comment by Balasubramanian-Sattanathan** [comment]
Hi Duzenko,

We have validated your reported problem “Resizing events in timeline week view fails with tons of console error spam” at our side. And we have tried to reproduce the issue by preparing the below sample using the “IsAllDay” field of the appointment like the below code snippet. Since we didn’t face the mentioned error while resizing after update the latest packages. We suspect that you could face the problem, due to misuse of the IsAllDay field. So we suggest you to refer the below sample and UG for more details.

**Code snippet:**
public data: Object[] = [
  {
    Id: 1,
    Subject: 'Testing-1',
    StartTime: new Date(2018, 1, 15, 10, 0),
    EndTime: new Date(2018, 1, 15, 11, 30),
    CategoryColor: '#00bdae',
    IsAllDay: true
  }, {
    Id: 2,
    Subject: 'Testing-2',
    StartTime: new Date(2018, 1, 15, 12, 0),
    EndTime: new Date(2018, 1, 15, 13, 30),
    CategoryColor: '#357cd2',
    IsAllDay: false
  }
];



**Sample:** https://stackblitz.com/edit/angular-gwnkze?file=app.component.ts
**UG:** https://ej2.syncfusion.com/angular/documentation/schedule/appointments/#all-day-events

Kindly refer and try the above sample, let us know the below details if the problem is not solved at your side.
-	Share scheduler related code snippets along with replication steps
-	Share the package details

**Comment by duzenko** [comment]
I was wrong. This has nothing to do with component upgrade.
We have had a change in our code that saved an event returned by the scheduler component to angular store.
The scheduler component keeps a reference to that event and when user resizes it in UI your code crashes because angular store marks it as read only.

**Comment by sellakumark** [comment]
@duzenko - when you resize the scheduler element alone we need to call refresh method manually to update UI, otherwise, when you resize the window the scheduler automatically refreshes the UI.
