### ISSUE TITLE
<ejs-richtexteditor> inline mode error when color property is displayed in mobile view.

### ISSUE THREAD

**Issue by nipuna777** [syncfusion/ej2-angular-ui-components#12]
When we have the inline rich text editor with a color property('Background', 'FontColor'), and try to open it in a mobile view(We need to use a device or Device emulation in Chrome), the component errors out and displays the color picker opened as follows:

![inline editor bug](https://user-images.githubusercontent.com/5859290/53676094-cce9fd00-3cd8-11e9-9a00-e23a1ffd129d.PNG)

In the console we get the following error stack trace:

```
ERROR TypeError: Cannot read property 'id' of undefined
    at e.renderColorPickerDropDown (constant.js:31)
    at eval (constant.js:31)
    at Array.forEach (<anonymous>)
    at n.renderColorPickerInput (constant.js:31)
    at n.renderColorPicker (constant.js:31)
    at t.notify (dom.js:256)
    at RichTextEditorComponent.r.notify (dom.js:256)
    at n.checkToolbarResponsive (constant.js:31)
    at n.renderToolbar (constant.js:31)
    at t.notify (dom.js:256)
```

Please find the modified StackBlitz from the demo example here:
https://stackblitz.com/edit/angular-ughe4q

To reproduce the error:
1. Open the  preview in a new window
2. Open the developer tools and inspect it as a mobile device
3. Reload the page

**Comment by PrinceOliver** [comment]
Hi @nipuna777,

We have validated the reported issue in our EJ2 RichTextEditor. We are considering this as a defect in our end. The fix for the issue will be included in our upcoming 2019 Volume 1 release. You can now track the current status of your request, review the proposed resolution timeline, and contact us for any further inquiries through this link: https://www.syncfusion.com/feedback/5050/

Regards,
Prince

**Comment by nipuna777** [comment]
> We have validated the reported issue in our EJ2 RichTextEditor. We are considering this as a defect in our end. The fix for the issue will be included in our upcoming 2019 Volume 1 release. You can now track the current status of your request, review the proposed resolution timeline, and contact us for any further inquiries through this link: https://www.syncfusion.com/feedback/5050/

Thank you for the follow up. I will track the task through the link you've provided.

**Comment by PrinceOliver** [comment]
Hello @nipuna777,

Thank you for your patience.

We have fixed the reported issue in our end and the fix is available in our 2019 Volume 1 beta release. To download the latest release, kindly refer to the following link: https://www.syncfusion.com/forums/143309/essential-studio-2019-volume-1-beta-release-v17-1-0-32-is-available-for-download

Kindly refer to the following links for further reference

Release notes section: https://github.com/syncfusion/ej2-angular-ui-components/releases/tag/v17.1.32-beta 
Sample link: https://stackblitz.com/edit/angular-ughe4q

Please let us know if you need any further assistance on this.

Regards,
Prince

**Comment by Sridhar-Narasimhan** [comment]
Closing the issue due to inactivity for a long time and solution already provided.
