### ISSUE TITLE
Row selection problem of gantt

### ISSUE THREAD

**Issue by yxrgds** [syncfusion/ej2-angular-ui-components#139]
There is a [simple](https://stackblitz.com/edit/angular-6iqyec?file=app.component.ts).

When I try to multi select with ctl key pressed,  it responsed slowly as I selected to the fourth row. But it is normal in this [page](https://angular-6iqyec.stackblitz.io/). Actually, we have this slow responsing problem with single row selection too in our project. But is can not always reproduce. Maybe they are of the same cause.

**Comment by yxrgds** [comment]
And there is a another tiny problem，it triggered row select event twice when selecting row with right click.

**Comment by gopinathmuniraj** [comment]
Hi Yxrgds, 
Thanks for contacting Syncfusion support. 
We have analyzed your query. Please find the below response. 
**Query1: When I try to multi select with ctl key pressed, it responsed slowly as I selected to the fourth row 
Solution:** 
As we have checked form our side, the multi-selection is working properly on selecting more number of rows. Please let us know your use case. It will be helpful for us to reproduce the problem and provide you with the proper solution as soon as possible. 
**Query2: And there is another tiny problem, it triggered row select event twice when selecting row with right click. 
Solution:** 
We are also able to reproduce to reported problem that, the rowSelected event is triggered twice. We have logged a bug report for this. The status can be tracked through below feedback link. 
Feedback link: https://www.syncfusion.com/feedback/20208/rowselected-event-is-triggered-twice-while-opening-context-menu  
The fix will be included in our 2020 Volume 4 release, which is expected to be rolled out on end of December 2020. 
Thanks for your patience until then. 
Regards, 
Gopinath M

**Comment by gopinathmuniraj** [comment]
Hi Yxrgds,
We are glad to announce that our Essential Studio 2020 Volume 4 release v18.4.0.30 is rolled out and is available for download under the following link.
https://www.syncfusion.com/forums/160733/essential-studio-2020-volume-4-release-v18-4-0-30-is-available-for-download
In that release, we have included the fix for the issue – “Row selected Event is triggered twice while opening context menu”, which is mentioned in the feedback 20208. We have prepared a sample. Please get the sample from below link.
Sample: https://stackblitz.com/edit/angular-ga7zr6?file=app.component.ts 
We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.
Regards,           
Gopinath M
