### ISSUE TITLE
how to use gantt context menu with multiple row selection?

### ISSUE THREAD

**Issue by yxrgds** [syncfusion/ej2-angular-ui-components#145]
when I select several rows and right click to open the context menu， only the row where I right clicked got selected, while I expect all the rows I selected before is still selected If I right click on the row I selected before.

**Comment by gopinathmuniraj** [comment]
Hi Yxrgds, 
Thanks for contacting Syncfusion support. 
We have analyzed your query. The behavior of the context menu items is, to update, delete, etc., the selected record. And it will not do it all the selected records. This is the reason to deselect the previously selected rows and context menu will open on the recently selected row alone. Because it will do the required actions for single record only.  
So, please share us your use case that why are you requiring to maintain the previously selected records to be selected even after the context menu opening. These details will helpful for us to understand your requirement and assist you better. 
Thanks, 
Gopinath M

**Comment by yxrgds** [comment]
> Hi Yxrgds,
> Thanks for contacting Syncfusion support.
> We have analyzed your query. The behavior of the context menu items is, to update, delete, etc., the selected record. And it will not do it all the selected records. This is the reason to deselect the previously selected rows and context menu will open on the recently selected row alone. Because it will do the required actions for single record only.
> So, please share us your use case that why are you requiring to maintain the previously selected records to be selected even after the context menu opening. These details will helpful for us to understand your requirement and assist you better.
> Thanks,
> Gopinath M

Hi gopinathmuniraj ,
Thanks for your reply.
We custom our own context menu include batch moving up and down tasks,etc. So we require to maintain the previously selected records.

**Comment by yxrgds** [comment]
I noticed that the latest version of  gantt had supported this feature. 
Thanks!
