### ISSUE TITLE
when opening word document in document editor I got this message Failed to load the file

### ISSUE THREAD

**Issue by elbaza** [syncfusion/ej2-angular-ui-components#16]

**Comment by RamyaThiru** [comment]
Hi,

Our Document Editor control has server-side library dependent for importing word document. So, we suspect this problem may occurs due to problem in your web service. 
  
You can find more details about importing document in DocumentEditor from below documentation link. 
  
Help documentation : https://ej2.syncfusion.com/angular/documentation/document-editor/import/?no-cache=1#convert-word-documents-into-sfdt  
  

Note: If you experienced this in our online demo site, we are sorry to let you know. We faced a technical glitch and it is resolved now. 

Regards,
Ramya T

**Comment by Sridhar-Narasimhan** [comment]
Closing the issue due to inactivity for a long time and solution already provided.
