### ISSUE TITLE
'Restrict Editing' and 'Form Field' buttons on Angular Document Editor get darker on every click

### ISSUE THREAD

**Issue by gauravbnsl** [syncfusion/ej2-angular-ui-components#165]
## Steps to reproduce:

1. Go to https://ej2.syncfusion.com/angular/demos/#/material/document-editor/default
2. Find the "Form Field" button on the toolbar
3. Keep clicking on it constantly

## After 1 click

![image](https://user-images.githubusercontent.com/25008254/114922464-53c2ab00-9e49-11eb-8e1f-f62aeb80cd43.png)

## After 3 clicks

![image](https://user-images.githubusercontent.com/25008254/114922504-62a95d80-9e49-11eb-984f-3002602adeb1.png)

## After 5 clicks

![image](https://user-images.githubusercontent.com/25008254/114922557-75239700-9e49-11eb-9ffd-4b5eb8cb1224.png)

**Comment by gunasekarant** [comment]
Hi @gauravbnsl ,

We have considered the reported issue as bug and logged the defect report. We will fix this issue and include in our EJ2 patch release which scheduled on May 5, 2021. 

You can track the status of feature through below feedback link:  
https://www.syncfusion.com/feedback/24578/opacity-issue-in-document-editor-toolbar 

Regards
Gunasekaran

**Comment by gauravbnsl** [comment]
Thanks @gunasekarant!

**Comment by gunasekarant** [comment]
Hi @gauravbnsl ,

We are glad to announce that our patch release (v19.1.64) is rolled out successfully and in this release, we have added the fix for reported issue.

Please upgrade to the latest version packages to resolve this issue.
https://www.npmjs.com/package/@syncfusion/ej2-angular-documenteditor 

Feedback link: https://www.syncfusion.com/feedback/24578/opacity-issue-in-document-editor-toolbar

Regards
Gunasekaran
