### ISSUE TITLE
Initialize ejs-schedule to a specific view

### ISSUE THREAD

**Issue by duzenko** [syncfusion/ej2-angular-ui-components#168]
Hi, I have an issue similar to https://github.com/syncfusion/ej2-javascript-ui-controls/issues/73
This time I need to switch to a view that user had the last time (saved in local storage)
We also need to respect per-view interval and grouping when switching
The workaround was to switch per-view `isSelected` property but as we have many views in the same scheduler it becomes too cumbersome. Has this been fixed in the recent versions?
Sample: https://stackblitz.com/edit/ej2-angular-schedule-view-customization-sample-6ev81v?file=app.component.html
Starting problem: the views don't switch via the select control on top

**Comment by Hareesh22** [comment]
Dear Customer,
 
Greetings from Syncfusion Support..!
 
We have modified your shared sample based on your shared query “the scheduler views don’t switch while selecting it from the select option” in that you have rendered the two-way bindings for both selected value for the Select (Dropdown) control and currentView property of Scheduler. On that scenario if we switch the select control then the value will be applied for the currentView property too. Since, the currentView property won’t take “Crew-week, 2month” which results the reported issue. And the sample can be viewed from the following link.
 
**Sample**: https://stackblitz.com/edit/ej2-angular-schedule-view-customization-sample-ffch3f?file=app.component.html 

```
<select clrSelect name="options" [(ngModel)]="currentSchedulerView">
    <option value="Month">Month</option>
    <option value="TimelineWeek">Crews</option>
</select>
 
<ejs-schedule width="100%" height="44rem" #scheduleObj [showHeaderBar]="false" [selectedDate]="schedulerDate" [eventSettings]="eventSettings" [views]="views" [currentView]="currentSchedulerView" [showQuickInfo]="false" [rowAutoHeight]="true" (created)="onCreated()">
  <e-views>
        <e-view option="Month" [eventTemplate]="eventInside" [interval]="2"></e-view>
	<e-view option="TimelineWeek" [eventTemplate]="eventInside" [timeScale]="timeScale" [group]="group"></e-view>
    </e-views>
    <e-resources>
	<e-resource field="crews" title="Crew" [dataSource]="crews" [allowMultiple]="true" name="Crews" textField="name" idField="id">
	</e-resource>
    </e-resources>
</ejs-schedule>
```
Kindly try the above solution and get back to us if you need any further assistance.
 
Regards,
Hareesh

**Comment by duzenko** [comment]
Thanks, but there can't be direct binding because we also need e.g. '1 Month' and '2 Months' options in the select control

**Comment by vinithadevi-murugan** [comment]
Dear Customer,

Thanks for your update.

We have modified our previously shared sample with views property like below code to achieve your requirement and same can be available in following link.

App.component.html
[views]="views" 

App.component.html
views = [{ option: "Month", interval: "1", displayName: "1 Month" },
  { option: "Month", interval: "2", displayName: "2 Month" },
  { option: "Month", interval: "3", displayName: "3 Month" },
  { option: "Month", interval: "5", displayName: "5 Month" },
  { option: "TimelineWeek", interval: "1", timeScale: { interval: 720, slotCount: 1 }, group: { resources: ["Crews"], allowGroupEdit: true } },
  ];

  schedulerDate = new Date();
  public currentSchedulerView1 = localStorage.getItem("view") as UserSchedulerView ?? "TimelineWeek";

  switchView() {
    var view = localStorage.getItem("view").trim();
    var interval = localStorage.getItem('interval').trim();
    this.views.filter(e => {
      if (e.option == view && e.interval == interval) {
        e.isSelected = true;
      } else {
        e.isSelected = false;
      }
    });
    this.scheduleObj.refresh();
  }

set currentSchedulerView(view: UserSchedulerView) {
    var viewDetail = (view.indexOf('-') > 0) ? view.split('-') : [view];
    localStorage.setItem("view", viewDetail[0]);
    localStorage.setItem("interval", (viewDetail.length > 1) ? viewDetail[1] : '1');
    this.switchView();
    // this.switchSchedulerView();
  }


Sample: https://stackblitz.com/edit/ej2-angular-schedule-view-customization-sample-updated-lytny4 

Kindly try the above sample and get back to us if you need any further assistance.    
   
Regards,   
Vinitha

**Comment by duzenko** [comment]
Thanks, but something appears to be wrong with your sample
I selected ''2 Month", refreshed the page and the select control is empty and the calendar view is "1 month"

**Comment by Balasubramanian-Sattanathan** [comment]
Hi Duzenko,

Thanks for the reply.

We have validated the reported problem and resolved in the below sample. In the below sample, the scheduler view will be retained properly in the local storage and the dropdown value also will be changed properly.

Sample: [https://stackblitz.com/edit/ej2-angular-schedule-view-customization-sample-updated-zd6nyy?file=app.component.html](url)

Kindly refer to the above sample and let us know if you need further assistance.

Regards,
Balasubramanian S

**Comment by Hareesh22** [comment]
Hi Duzenko, 

Thanks for the reply. 

We have modified your shared sample at our end based on your shared queries, which can be viewed from the following link, 
https://stackblitz.com/edit/ej2-angular-schedule-view-customization-sample-updated-h9xo1r?file=app.component.ts  

**_Q1: getCurrentViewDates() returns empty array after the initial page load. I need the date range to query the backend service for events._** 

This can be achieved using dataBound event of our Scheduler. 

```
  onDataBound() { 
    if (this.flag && !isNullOrUndefined(localStorage.getItem('view'))) { 
      this.switchView(); 
      this.flag = false; 
    } 
    this.calendarDates = this.scheduleObj.getCurrentViewDates(); 
    console.log('switchView', this.calendarDates.length); 
  } 
```
**_Q2: actionComplete does not fire when the user changes the selection in the dropdown._** 

Since you have disabled the scheduler toolbar and that could be the reason for the above issue “actionComplete event is not triggering while switching the views” and for that, we have enabled the showHeaderBar property of our scheduler. 

**Note**: If you need to trigger the actionComplete event for view navigation without scheduler header, kindly use the below CSS. 

```
.e-schedule-toolbar-container { 
    display: none; 
} 
```

Kindly try the above solution and get back to us if you need any further assistance. 

Regards, 
Hareesh

**Comment by duzenko** [comment]
@Hareesh22 
Appreciate your help
The select on the top does not show the saved value on page reload

**Comment by Nevitha-Ravi** [comment]
Hi Duzenko,

Thanks for your update.

We have modified the sample with the below changes using select’s **change** event and schedule’s **navigating** event.
•	maintain the selected value in select option on initial load, reload and view navigation in scheduler.
•	Current view and select value option are always same.
•	Persistence is maintained now for view and select option which can be changed through select dropdown, switching view in scheduler.

**sample**: https://stackblitz.com/edit/ej2-angular-schedule-view-persistence-with-interval-option?file=app.component.ts

Please try the sample and let us know if you need any further assistance on this.

Regards,
Nevitha

**Comment by duzenko** [comment]
@Nevitha-Ravi thank you
Unfortunately the integrated toolbar gets in the way of our UI
E.g. we need to show the timeline view named "Crews" 
Please advise

**Comment by Nevitha-Ravi** [comment]
Hi Duzenko,

Thanks for your update.

We have changed the timeline week to crews in the following sample.
https://ej2-angular-schedule-view-persistence-with-interval-opti-bohrh1.stackblitz.io/

Also we have hided the header bar, but the event is not trigger with the viewNavigate option at our end. Could you please share the following details?
•	In which scenario the event trigger with viewNavigate type?
•	Share the issue depicting sample and video demo

Regards,
Nevitha

**Comment by duzenko** [comment]
Thank you very much
I think we're good for now
I will raise another issue if I run into any problems
