### ISSUE TITLE
Change the days format from 'Su' to 'Sun'

### ISSUE THREAD

**Issue by anoopyadav-kiwi** [syncfusion/ej2-angular-ui-components#17]
Hello Team,

I want to change the current day's format(Su, Mo, Tu, We, Th, Fr, Sa) to (Sun, Mon, Tue, Wed, Thu, Fri, Sat).

Please help ASAP.

Thanks in advance.

**Comment by BerlyChristopher94** [comment]
Hi Anoopyadav,

Currently, we have not provided the support for change the day header format for DatePicker component directly. We are working to achieve your requirement as the work around solution. We will validate and update the further details in one business day (11th April 2019). We appreciate your patience until then.

Please let me know if you have any concerns,

Regards,
Berly B.C

**Comment by BerlyChristopher94** [comment]
Hi Anoopyadav,

We achieved your requirement (“Change the day header format instead of Su, Mo, Tu... display Sun, Mon, Tue... for DatePicker component”) by override the default header format “**short**” as “**abbreviated**” in our private **getCultureValues()** method as like in the below code example. 

**[app.component.html]**

```html
<ejs-datepicker  (created)="onCreate($event)"></ejs-datepicker>
```

**[app.component.ts]**

```ts
onCreate(args) {
    (DatePicker as any).prototype.getCultureValues = function (option, option2) {
      var culShortNames = [];
      var cldrObj;
      if (this.locale === 'en' || this.locale === 'en-US') {
        cldrObj = (getValue('days.stand-alone.abbreviated', getDefaultDateObject())); // To show the day header format as "Sun", "Mon" etc.
      }
      else {
        cldrObj = (this.getCultureObjects(cldrData, '' + this.locale));
      }
      for (var _i = 0, _a = Object.keys(cldrObj); _i < _a.length; _i++) {
        var obj = _a[_i];
        culShortNames.push(getValue(obj, cldrObj));
      }
      return culShortNames;
    }
  }
```

Please find the sample from the below link.

**Sample Link:** https://stackblitz.com/edit/angular-kjakvf-uxixdc?file=app.component.html 

Also, we have logged the reported requirement as a feature request already at our end and this support will be included in any one of our upcoming releases. You can track the status of your request, review the proposed resolution timeline, and contact us for any further inquiries through the below feedback link. Please log in to the feedback portal tool using Direct trac credentials. 

**Feedback Link**: https://www.syncfusion.com/feedback/5744/provide-option-for-change-the-day-header-format-in-all-the-picker-components

Regards,
Berly B.C

**Comment by anoopyadav-kiwi** [comment]
Thanks for your update.

Can you please tell me where I need to declare 'getCultureObjects' function because when I used your code it gives the error for 'getCultureObjects' function.

**Comment by BerlyChristopher** [comment]
Hi Anoopyadav,

We have overridden the default day header format in our DatePicker private method “**getCultureValues**” to achieve your requirement. For this we need to import the **DatePicker** from “**ej2-calendars**” package as given in the code example, since “**getCultureObjects**” is the private method in the DatePicker source.

**[app.component.ts]**
```ts

import { DatePicker } from '@syncfusion/ej2-calendars';
import { getDefaultDateObject, getValue, cldrData } from '@syncfusion/ej2-base';
```

Regards,
Berly B.C

**Comment by Sridhar-Narasimhan** [comment]
Closing the issue due to inactivity for a long time and solution already provided.
