### ISSUE TITLE
Emergency: Rich text editor- Copy past from MS Office is not working. But work fine on React and Vue demo

### ISSUE THREAD

**Issue by arunjoshtech** [syncfusion/ej2-angular-ui-components#174]
Dear Team,
I angular demo I selected all demo content and deleted , then copy pasted attached MS office content nothing past and found attached errors in console. 
It is working fine in React and Vuejs demo.

It is major bug in Angular Rich text editor. Kindly give high priority and resolve it.

![copy past ANGULAR RICH TEXT EDITOR ERROR_WORKING FINE IN REACT AND VUE](https://user-images.githubusercontent.com/63642104/118312086-75798580-b50e-11eb-9de9-c4d882c7c1b8.png)
[MS OFFICE COPY PAST NOT HAPPENING BUT IN REACT AND VUE WORKING.docx](https://github.com/syncfusion/ej2-angular-ui-components/files/6480524/MS.OFFICE.COPY.PAST.NOT.HAPPENING.BUT.IN.REACT.AND.VUE.WORKING.docx)
![error copay past  not in angular but happening in react and vue](https://user-images.githubusercontent.com/63642104/118312111-7dd1c080-b50e-11eb-93e5-746cac31f0df.PNG)

**Comment by revanthSyncfusion** [comment]
Hi Arunjosh,



Greetings from Syncfusion support.



We have validated your query **“In the angular demo, deleting all content and pasting the content from attached MS Word document doesn’t paste the content”.**

This issue occurred because the property **‘maxLength’** is set with a value **‘1000’**, where the pasted content has more than 1000 characters so, the paste is prevented. This can be resolved by setting the **‘maxLength’** with a larger value or removing the **‘maxLength’** property. We have prepared a sample for your reference,

**Code Snippet:**

```
<ejs-richtexteditor #toolsRTE id="alltoolRTE" [maxLength]="3000">
  . . .
</ejs-richtexteditor>
```
_**Note:** Remove the **‘maxLength’** configuration will allow the Rich Text Editor to accept infinite characters._

**Sample:** https://stackblitz.com/edit/angular-5t2qsk-xpjwdu?file=app.component.html

Please check the code snippet and the sample and let us know if it resolves the issue.

Regards,
Revanth
