### ISSUE TITLE
Scyncfusion module works unusual on refresh

### ISSUE THREAD

**Issue by Sachinrana99** [syncfusion/ej2-angular-ui-components#207]
Hi. I have installed and added <ejs-schedule></ejs-schedule> component inside my angular project. On routing i am able to view the component as per docs.While refreshing the window, toolbar gets hidden and works differently.Attaching pictures for reference.
Angular Version - 12.2.0
syncfusion/ej2-angular-schedule: 19.3.53

**Before refresh**:

![original](https://user-images.githubusercontent.com/44962383/142727201-9145b2e8-de10-498a-aa0e-8685415f2e7c.png)

**After refresh** :
![refresh](https://user-images.githubusercontent.com/44962383/142727203-ccd173d9-500b-4f1e-ac22-19b0d2ebd9c2.png)

.

**Comment by VengateshManiraj** [comment]
Hi @Sachinrana99,

The reported issue has been occurred due to the Hot Module Replacement([HMR](https://blog.angular.io/version-11-of-angular-now-available-74721b7952f7)).  To resolve your problem, please import the Scheduler-related styles within the module which is used to render the scheduler and avoid the global style referring. 

Regards,
Vengatesh
