### ISSUE TITLE
DOCUMENT EDITOR: TABLE CONTENT COPY PASTE GETTING DEFORMATION

### ISSUE THREAD

**Issue by arunjoshtech** [syncfusion/ej2-angular-ui-components#208]
Dear Team,
While copy paste the table from MS word the table getting deformatted as shown in attached images.
I tried both in Apple mac and Windows PC. Same issues produced.
The same deformation happening in Asp.net core, vuejs and Reactjs too.

[word document for error reproduction.docx](https://github.com/syncfusion/ej2-angular-ui-components/files/7587028/word.document.for.error.reproduction.docx)
![actual word doc_synfusion issues](https://user-images.githubusercontent.com/63642104/143002271-ca41f902-8060-46b6-af15-4d2019622187.png)
![doc editor_deformatted_synfusion](https://user-images.githubusercontent.com/63642104/143002280-6e939b8c-a58d-40e8-827a-7f55839acb8f.png)

**Comment by arunjoshtech** [comment]
Dear Team, Does it need any other details to make this issues more understanding.

**Comment by arunjoshtech** [comment]
Dear Team,
Any confirmation about the issues?

**Comment by arunjoshtech** [comment]
Dear Team, can I expect any reply or advise on this please

**Comment by arunjoshtech** [comment]
Dear team, in recent update also this issue is not fixed. Hope you may give importance to this issues. 
Thank you

**Comment by Suriya-Murugan** [comment]
Hi Arunjoshtech,
Can you please try reproducing the reported issue in latest version(19.4.48) and please check in below demo site also?

https://ej2.syncfusion.com/angular/demos/#/bootstrap5/document-editor/default 
If still facing issue, We suspect that the reported problems are might be due to the contents in the input word document which used at your end. We need to investigate with the contents in your input Word document to reproduce the exact problem at our end. So, could you please provide us the input Word document which used at your end. Thereby, we will analyze further and provide you the appropriate solution at the earliest.
 
Note: If you have any confidential data in your Word document, please replace with some dummy data and provide us the same. We just need your document to recreate the problem you face.

Regards,
Suriya M.

**Comment by syncsiva** [comment]
This issue has not had any activity for 2 weeks. Closing for housekeeping purposes. Please feel free to reopen it if you have more information that can help us investigate the issue further.

**Comment by arunjoshtech** [comment]
Dear Team I tried with your Global website with the same content and still the issue  is persist.
Sorry for the late reply due to personal health issues. I have attached screen shot which taken by today.
![table mis allignment](https://user-images.githubusercontent.com/63642104/155480823-e4fe98f3-4098-4135-bb56-3e6a33c7172e.PNG)
.

**Comment by arunjoshtech** [comment]
> 

I have attached content as doc in first issues itself. kindly check with that content
