### ISSUE TITLE
Word Editor: Second page cannot edit or Change

### ISSUE THREAD

**Issue by arunjoshtech** [syncfusion/ej2-angular-ui-components#213]
Dear Team,
when I work on the document I found repeatedly that second page of word processor goes not usable like cursor cannot move, cant do copy paste and any kind of editing in second page but it will work on first page as usual.
I have added error code found in browser console herewith for your  reference

main.1d1df2ae3dab56b8d621.js:1 ERROR TypeError: Cannot read properties of undefined (reading 'isEmpty')
    at Wf.isCursorInFooterRegion (8.99e883608aafdf693d55.js:1)
    at HTMLDivElement.Rp.onMouseDownInternal (8.99e883608aafdf693d55.js:1)
    at l.invokeTask (polyfills.696cbe404fe3be1f9a9c.js:1)
    at Object.onInvokeTask (main.1d1df2ae3dab56b8d621.js:1)
    at l.invokeTask (polyfills.696cbe404fe3be1f9a9c.js:1)
    at a.runTask (polyfills.696cbe404fe3be1f9a9c.js:1)
    at u.invokeTask [as invoke] (polyfills.696cbe404fe3be1f9a9c.js:1)
    at m (polyfills.696cbe404fe3be1f9a9c.js:1)
    at HTMLDivElement.y (polyfills.696cbe404fe3be1f9a9c.js:1)

**Comment by arunjoshtech** [comment]
Dear Team,
Error code screen shot is attached here. please check.

![synfusion word second page](https://user-images.githubusercontent.com/63642104/147443893-566d487c-99f7-452a-a760-20b4b3e308bb.jpeg)

**Comment by Suriya-Murugan** [comment]
Hi Arunjoshtech,

We suspect that the reported problems are might be due to the contents in the input word document used at your end. We need to investigate the contents in your input Word document to reproduce the exact problem at our end. So, could you please provide us with the input Word document used at your end? Thereby, we will analyze further and provide you with the appropriate solution at the earliest.
 
Note: If you have any confidential data in your Word document, please replace it with some dummy data and provide us the same. We just need your document to recreate the problem you face.

Regards,
Suriya M.

**Comment by syncsiva** [comment]
This issue has not had any activity for 2 weeks. Closing for housekeeping purposes. Please feel free to reopen it if you have more information that can help us investigate the issue further.

**Comment by arunjoshtech** [comment]
> This issue has not had any activity for 2 weeks. Closing for housekeeping purposes. Please feel free to reopen it if you have more information that can help us investigate the issue further.

Dear Suriya,
I didn't login to GitHub due to personal reason and your team not responded for this issues from the day I created the issues.
Well This issues we faced multiple times with different pc and files. Once we clear and copy paste it, it was working. so the issue is not related to particular document of file. we felt it is some thing related to Word editor control.
