### ISSUE TITLE
WORD EDITOR: TABLE GETTING DEFORMATION

### ISSUE THREAD

**Issue by arunjoshtech** [syncfusion/ej2-angular-ui-components#217]
Dear Team,
While copy paste the table from MS word the table getting deformatted as shown in attached images.
I tried both in Apple mac and Windows PC. Same issues produced.
The same deformation happening in Asp.net core, vuejs and Reactjs too.

**Comment by Suriya-Murugan** [comment]
Hi Arunjoshtech,

We suspect that the reported problems are might be due to the contents in the input word document which used at your end. We need to investigate with the contents in your input Word document to reproduce the exact problem at our end. So, could you please provide us the input Word document which used at your end. Thereby, we will analyze further and provide you the appropriate solution at the earliest.
 
Note: If you have any confidential data in your Word document, please replace with some dummy data and provide us the same. We just need your document to recreate the problem you face.

Regards,
Suriya M.

**Comment by syncsiva** [comment]
This issue has not had any activity for 2 weeks. Closing for housekeeping purposes. Please feel free to reopen it if you have more information that can help us investigate the issue further.
