### ISSUE TITLE
Gantt - labelSettingsRightLabel

### ISSUE THREAD

**Issue by aaronbach** [syncfusion/ej2-angular-ui-components#223]
We are using @syncfusion/ej2-angular-gantt in the current latest version 19.4.56.
We are using the TaskLabelTemplates like showed in this example: https://ej2.syncfusion.com/angular/demos/#/bootstrap5/gantt/tasklabel-template

`<ng-template #labelSettingsLeftLabel let-data>` and <ng-template #labelSettingsRightLabel let-data>` are working like described in the docs, but we cannot get any data in `<ng-template #labelSettingsTaskLabel let-data>`. The variable `data` is always empty.

I cannot find any additional docs about `labelSettingsTaskLabel` in the angular template notation. Am I missing smth, or is it a bug?

Best Aaron

**Comment by premkumarsudalaimuthu** [comment]
Hi Aaron ,

We have considered this as a bug from our side and have logged a bug report for it. You can track its status from the below feedback link.

Feedback: https://www.syncfusion.com/feedback/33602/taskbar-template-not-applied-when-zooming 

We will provide the fix for this issue in the patch release scheduled for April 13, 2022.

Regards,
Premkumar S

**Comment by aaronbach** [comment]
Thank you

**Comment by syncsiva** [comment]
Closing for housekeeping purposes. The reported bug can be tracked through below feedback link further,
https://www.syncfusion.com/feedback/33602/taskbar-template-not-applied-when-zooming

Please feel free to reopen if you have any further queries.
