### ISSUE TITLE
Dropdown list width is not same as the dropdown control

### ISSUE THREAD

**Issue by sharathdaniel** [syncfusion/ej2-angular-ui-components#265]
When the dropdown is in a flex container with scroll, the dropdownlist width is not the same. There is a small difference in width.

Here is the [code](https://stackblitz.com/edit/angular-hfxt5r?file=src%2Fapp.component.html).

Screenshot
![image](https://github.com/syncfusion/ej2-angular-ui-components/assets/5154064/dca99c93-4cbd-4b68-8cc8-bffcee2b603d)

**Comment by Kokila13081999** [comment]
We have considered the reported issue “**Dropdown list width is not same as the dropdown control**” as a bug from our end and the fix for the issue will be included with our upcoming patch release at the end of December.



**Disclaimer: “Inclusion of this solution in the weekly release may change due to other factors including but not limited to QA checks and works reprioritization.”**

**Comment by gsumankumar** [comment]
The reported issue has been successfully addressed in release version v24.1.44. Consequently, we are closing this ticket for administrative purposes. Should you have any additional questions or concerns, please feel free to reopen the ticket, and we will be more than happy to assist you further.
