### ISSUE TITLE
Getting this error after deleting node modules and reinstall.

### ISSUE THREAD

**Issue by vikash09** [syncfusion/ej2-angular-ui-components#27]
ERROR in node_modules/@syncfusion/ej2-splitbuttons/src/split-button/split-button.d.ts(85,5): error TS2424: Class 'DropDownButton' defines instance member function 'click', but extended class 'SplitButton' defines it as instance member property.

**Comment by EfkanKnz** [comment]
I have the same error. For a temporary solution I reinstalled an older version:
```
npm i @syncfusion/ej2-angular-charts@16.3.24 --save
```

**Comment by vinoth-Kumar-S** [comment]
Hi vikash09,

Good day to you.

We are glad to announce that our Essential JavaScript 2 patch release (v17.1.51) has been rolled out successfully and in this release, we have added the fix for issue “Name conflict occurs when function and property having same name in DropDownButton”. Now you can update latest package to resolve this issue in your end. 

Please refer the below documentation to update the Syncfusion npm package,
https://ej2.syncfusion.com/angular/documentation/common/how-to/update-npm-package/

Regards,
Vinoth Kumar S

**Comment by Sridhar-Narasimhan** [comment]
Closing the issue due to inactivity for a long time and solution already provided.
