### ISSUE TITLE
<ejs-textbox> focus handling not working

### ISSUE THREAD

**Issue by mszewcz** [syncfusion/ej2-angular-ui-components#3]
Please note, that following is not working:
```
<ejs-textbox
        [formControlName]="'someControlName'"
        [floatLabelType]="'Always'"
        [placeholder]="'Placeholder text'"
        [type]="'text'"
        (focus)="alert('focused')"
></ejs-textbox>
```
Focus event is not firing `alert`.

**Comment by PrinceOliver** [comment]
Hi Michal,

Thanks for using Syncfusion products

We have already logged this issue as bug and fixed internally. The fix for this issue has been included in the current updated package( ej2-inputs version 16.3.33). For your convenience, we have prepared simple sample with updated package.

Sample: https://stackblitz.com/edit/angular-cbc5mv

Regards,
Prince

**Comment by mszewcz** [comment]
Hi Prince. 

(focus) works fine with 16.3.33.
Thanks for the quick fix.

Regards,
Michal
