### ISSUE TITLE
ej2-angular-dropdowns": "^17.1.49" `change` event bug

### ISSUE THREAD

**Issue by cyphercodes96** [syncfusion/ej2-angular-ui-components#31]
Version: "@syncfusion/ej2-angular-dropdowns": "^17.1.49"

Replicated Version: https://stackblitz.com/edit/angular-4dy9dk

Replication Steps:
open select modal, select a country, press outside, check console.logs you shall see `changed!`

open select modal, select a country, and press ON the MULTI-SELECT FIELD

Expected: console.logs should show `changed!`

Currently Occuring: nothing in console.logs, change event not triggered / detected

**Comment by Gopigovin** [comment]
Hi Rawad Ahmad,

Thank you for taking your time to report this issue. This is a known issue in our end. The fix for this issue will be include in our Volume 2 2019 release, which is expected to be rolled out in the end of June 2019. 
You can now track the current status of the report, review the proposed resolution timeline, and contact us for any further inquiries through this link: https://www.syncfusion.com/feedback/6253/ 

Please let us know, if you have any concern on this. 

Regards,
Gopi G.

**Comment by PrinceOliver** [comment]
Hi @cyphercodes96,

Thank you for your patience.

We have fixed the reported issue in our end. The fix is included in the Volume 2, 2019 beta release (**v17.2.28-beta**). Kindly refer to the following release notes section: https://ej2.syncfusion.com/angular/documentation/release-notes/17.2.28/#multiselect 

We suggest you upgrade to the latest version to resolve the issue.

Regards,
Prince

**Comment by Sridhar-Narasimhan** [comment]
Closing the issue due to inactivity for a long time and solution provided already.
