### ISSUE TITLE
 Cannot access 'Node' before initialization

### ISSUE THREAD

**Issue by yilmazhasan** [syncfusion/ej2-angular-ui-components#47]
I am trying to use diagram-builder but although compilation is successful I am getting this error on browser:

Cannot access 'Node' before initialization - ej2-diagrams.es2015.js:8680 

at Module  @syncfusion/ej2-diagrams/dist/es6/ej2-diagrams.es2015.js 

I am using version of:
Angular CLI: 8.1.2
Node: 10.15.1

**Comment by gshyam93** [comment]
Hi Yilmazhasan, 
 
The reported issue occurs when target property not set as es5 in tsconfig.json file. By default, the target property value is es5. Could you please check the target property value of your sample? Still if you face issue, please share us more details such as modify the below sample or share your sample. 
 
Screenshot: 
![image](https://user-images.githubusercontent.com/8110169/62600630-f9034d00-b90c-11e9-9e85-97a2b373f2fb.png)
  
 
Sample: https://www.syncfusion.com/downloads/support/directtrac/general/ze/diagrambuildersample-2088822312 
 
Regards, 
Shyam G

**Comment by EmptyRedoubt** [comment]
Same issue here.  Changed the target to es5 and still get an error:

![image](https://user-images.githubusercontent.com/26556492/63380356-9b7eef80-c353-11e9-82dc-8113ae86083f.png)

![image](https://user-images.githubusercontent.com/26556492/63380413-b18cb000-c353-11e9-9fcd-63212702e00f.png)

**Comment by gshyam93** [comment]
Hi EmptyRedoubt,

Reported issue : Angular diagram breaks, when we set target as es6/es2015 in tsconfig file. 
  
We are glad to announce that our patch release (v17.2.47) is rolled out successfully and In that release, we have added the fix for reported issue.    
     
Please upgrade to the latest version packages to resolve this issue. 
https://www.npmjs.com/package/@syncfusion/ej2-diagrams  

Regards,
Shyam G

**Comment by Sridhar-Narasimhan** [comment]
We have already provided a solution. So we will close this issue.
