### ISSUE TITLE
When DataManager http call fails, no empyRow is created

### ISSUE THREAD

**Issue by gerhardboer** [syncfusion/ej2-angular-ui-components#66]
When the datamanager http call fails, and the backend returns an error, the following error is shown in the console:
"Error: Uncaught (in promise): TypeError: Cannot read property 'querySelector' of undefined
TypeError: Cannot read property 'querySelector' of undefined
at r.emptyRow"

stackblitz: https://stackblitz.com/edit/angular-thsbwe

**Comment by MaithiliyK** [comment]
Hi Gerhardboer,

Thanks for using syncfusion component.

We have checked the sample that you have shared with us, and we found that you have assigned the datamanager returned value to Angular Grid component as datasource as like below

<ejs-grid
  [dataSource]="data"
 . . . .
 </ejs-grid>

To overcome the reported issue, it is must to provide datasource(with data) or need to define the columns(if datasource is empty) while initializing the grid this is the default behavior of grid component.

For your convenience we have modified the sample by providing the columns(you can change the column definition based on your database columns) and also referring the component CSS(in index.html page) to load the control in proper structure.

https://stackblitz.com/edit/angular-b5vc3s 

And also we have noticed that you have defined the action failure event to know the exact issue of not rendering the component, but you have defined the event name as "onActionFailed" instead of actionFailure for action failure event the same can be resolved in the above sample.

Please get back to us if you need any further assistance. 

Regards,
Syncfusion Support

**Comment by gerhardboer** [comment]
Ah i did not know that you needed to supply columns if a datasource is empty. 
But wouldn't it be recommended to always define columns? or at least always when using an async call to show the columns?

This might be hinted at in the documentation to prevent misuse.
