### ISSUE TITLE
Using CLI buildOptimizer with builds after 17.2.52 breaks RichTextEditor

### ISSUE THREAD

**Issue by rosslavery** [syncfusion/ej2-angular-ui-components#74]
After upgrading to 17.3.x to gain access to the new `enableResize` option for the RichTextEditor, my application became unusable when building for production.

All of the errors stemmed from the fact that the default options for the component were not present or initialized, e.g. `toolbarSettings`. I began encountering errors complaining about each setting being undefined, and as I populated them, the next setting in the list would indicate it was undefined.

After downgrading back to 17.2.52, these errors went away, but obviously I lost access to the `enableResize` option.

Upgraded to 17.3.x builds again, this time disabling the @angular/cli configuration option for `buildOptimizer`, and this allowed the app to work in production mode.

I suspect the build optimization step is removing code that it believes is unused, but is actually in use, causing runtime errors but no build errors.

Difficult to provide a Stackblitz example, as we're dealing with CLI build-time issues. But very easy to replicate.

Seems possibly related to https://github.com/syncfusion/ej2-angular-ui-components/issues/52 .

Angular 8.2.X
Angular CLI 8.2.X (also tried 8.3.X as part of troubleshooting)

**Comment by pandiyarajm93** [comment]
Hi @rosslavery ,

Greetings from Syncfusion support.

We have validated the reported issue with the following configuration and facing only toolbar items alignment issue from our end. Because styles loaded after component initialized in DOM.

Currently, we are validating the issue and we will update the details on 8th November.

Angular CLI: 8.3.10
Node: 10.16.3
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.803.10
@angular-devkit/core         8.3.10
@angular-devkit/schematics   8.3.10
@angular/cli                 8.3.10
@schematics/angular          8.3.10
@schematics/update           0.803.10
rxjs                         6.4.0

**Screenshot:**
![image](https://user-images.githubusercontent.com/54373337/68296407-8dbb4980-00ba-11ea-91c1-8d8ace784586.png)

If it is not meet your requirement or if you are facing any other issue, then share any additional details or simple video. It will helpful for us to validate your issue and provide the solution as soon as possible.

Regards,
Pandiyaraj

**Comment by pandiyarajm93** [comment]
Hi @rosslavery ,

Sorry for delayed update.

We suggest you configure **target** option as **es5** in your application **tsconfig.json** file to resolve the **alignment issue of toolbar items**.

Regards,
Pandiyaraj
