### ISSUE TITLE
Grid does not reflect template changes

### ISSUE THREAD

**Issue by akushnikov** [syncfusion/ej2-angular-ui-components#8]
#### What is the expected behavior?

Grid component should reflect angular template changes

#### What is the current behavior?

Grid markup is broken after its template has been changed

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-zywrxz

#### Package versions:

```
"@syncfusion/ej2-angular-grids": "^16.4.44",
"@angular/animations": "^7.1.0",
"@angular/common": "^7.1.0",
"@angular/compiler": "^7.1.0",
"@angular/core": "^7.1.0",
"@angular/forms": "^7.1.0",
"@angular/http": "^7.1.0",
"@angular/platform-browser": "^7.1.0",
"@angular/platform-browser-dynamic": "^7.1.0",
"@angular/router": "^7.1.0",
```

**Comment by Pavithra15** [comment]
Hi @akushnikov 

Query: What is the expected behavior? Grid component should reflect angular template changes

We have analyzed your query and the grid columns are changed only when there is a change in the grid.column property. So after changing through templates, the changes will not reflect in the grid columns which is the default behavior. To achieve your requirement, we suggest rendering grid when there is a change in the column property through template as shown below,

Code Example:
```html
<ng-container *ngIf="columnChanged">
    <ejs-grid [dataSource]='data' allowReordering='true'>
        <e-columns>
          <ng-container *ngFor="let column of columns">
            ...
          </ng-container>
        </e-columns>
    </ejs-grid>
    </ng-container>
```
```typescript
onToggle() {
      this.columnChanged = false;
      this.columns = [
        {field: 'Title', headerText: 'Title', width: '150px', template: 'default'},
        {field: 'HireDate', headerText: 'Hire Date', width: '150px', template: 'date'},
        {field: 'ReportsTo', headerText: 'Reports To', width: '150px', template: 'default'}
      ];
      setTimeout(()=>{this.columnChanged = true;},0)
    }
```
[Sample](https://stackblitz.com/edit/angular-zywrxz-12k3dt?file=reorder.component.ts) 

Please get back to us for further assistance.

Regards,
Pavithra S.

**Comment by Sridhar-Narasimhan** [comment]
Solution provided and closing the issue due to inactivity for a long time.
