### ISSUE TITLE
Show undefined text populated in the editor, when am using the ngModel 

### ISSUE THREAD

**Issue by ramreddy123** [syncfusion/ej2-angular-ui-components#80]
<ejs-richtexteditor name="alertMsg" [(ngModel)]="model.alertMsg" #alertMsg="ngModel" required></ejs-richtexteditor>

How to set some init value in HTML..?

**Comment by pandiyarajm93** [comment]
Hi @ramreddy123 ,

Greetings from Syncfusion support.

We suggest you, configure `value` API in our RichTextEditor component instead of ngModel to bind initial value and access the current value from the editor.

API: https://ej2.syncfusion.com/angular/documentation/api/rich-text-editor/#value

We have prepared sample for your reference, check the below link
https://stackblitz.com/edit/angular-nvf4zk-qeiszg?file=app.component.html 

Regards,
Pandiyaraj

**Comment by ramreddy123** [comment]
Thank you..!!!!
