### ISSUE TITLE
How to get the formatted HTML when am clicking on the source button

### ISSUE THREAD

**Issue by ramreddy123** [syncfusion/ej2-angular-ui-components#81]
When am clicking on the source button am getting inline code format as in the screenshot

![gt](https://user-images.githubusercontent.com/5622293/71799426-4251f700-307b-11ea-8cfb-579ab048ac1d.png)

How can we achieve this without the third party integration like codemirror..?

Can you help me...?

**Comment by Indrajith-Sync** [comment]
Hi ramreddy123,

We have validated the reported query, to format the code block in the innerHTML you can use the js-beautify to format it.

You can refer the following steps to be followed

**index.html**

`<script src="https://cdnjs.cloudflare.com/ajax/libs/js-beautify/1.10.2/beautify-html.js"></script>`

Can bind the actionComplete event to the RichTextEditor and in order to beautify the RichTextEditor value you can define as like below.

**app.component.ts**

> import { html_beautify } from 'js-beautify'
> 
> public actionCompleted(e: ActionCompleteEventArgs): void {
>     if (e.requestType === "SourceCode") {
>       const textArea: HTMLTextAreaElement = document.querySelector(
>         ".e-rte-srctextarea"
>       );
>       //Beautify html elments
>       textArea.value = html_beautify(textArea.value, { "indent-size": 2 });
>     }
>   }

Sample for reference:- https://stackblitz.com/edit/angular-9uueto-7snnmz?file=app.component.ts

Regards,
Indrajith

**Comment by rajendranr-5483** [comment]
@ramreddy123 

We are closing this thread now due to long pending. Please reopen this thread if you have any other concerns about your requirement.
